# Generated by Django 3.0.7 on 2020-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie',
            field=models.FloatField(default=0),
        ),
    ]
